export const product = [
    {
        id:1,
        name: "Iphone 7 Plus - Rose gold",
        url: "/IPhone_7_Plus.png",
        price: 2800000,
        type: 'smartphone',
        popular: true,
        new: false,
        recommended: false,
        stock: 8,
        specifications: {
            brand: 'Apple',
            size: '5.5 inches',
            display: 'Retina IPS LCD, 625 nits (typ)',
            resolution: '1080 x 1920 pixels, 16:9 ratio (~401 ppi density)',
            os: 'iOS 10.0.1',
            prosesor: 'Apple A10 Fusion (16 nm), Quad-core 2.34 GHz (2x Hurricane + 2x Zephyr)',
            gpu: 'PowerVR Series7XT Plus (six-core graphics)',
            memory: '3GB RAM',
            storage: '256GB NVMe',
            network: 'GSM/CDMA/HSPA/EVDO/LTE',
            camera: 'Belakang: 12 MP, f/1.8, 28mm (wide), 1/3.0", PDAF, OIS 12 MP, f/2.8, 56mm (telephoto), 1/3.6", AF, 2x optical zoom. Depan: 7 MP, f/2.2, 32mm (standard)',
            bluetooth: '4.2, A2DP, LE',
            usb: 'Lightning, USB 2.0',
            sensor: 'Fingerprint (front-mounted), accelerometer, gyro, proximity, compass, barometer',
            battery: 'Li-Ion 2900 mAh, non-removable (11.1 Wh)'
        }
    },
    {
        id:2,
        name: "Iphone Xs Max - White",
        url: '/iphone-x-silver.png',
        price: 4200000,
        type: 'smartphone',
        popular: true,
        new: false,
        recommended: true,
        stock: 10,
        specifications: {
            brand: 'Apple',
            size: '6.5 inches',
            display: 'Super Retina OLED, HDR10, Dolby Vision, 625 nits (HBM)',
            resolution: '1242 x 2688 pixels, 19.5:9 ratio (~458 ppi density)',
            os: 'iOS 12, upgradable to iOS 18.6',
            prosesor: 'Apple A12 Bionic (7 nm), Hexa-core (2x2.5 GHz Vortex + 4x1.6 GHz Tempest)',
            gpu: 'Apple GPU (4-core graphics)',
            memory: '4GB RAM',
            storage: '256GB NVMe',
            network: 'GSM/CDMA/HSPA/EVDO/LTE',
            camera: 'Belakang: 12 MP, f/1.8, 26mm (wide), 1/2.55", 1.4µm, dual pixel PDAF, OIS 12 MP, f/2.4, 52mm (telephoto), 1/3.4", 1.0µm, PDAF, OIS, 2x optical zoom. Depan: 7 MP, 7 MP, f/2.2, 32mm (standard) SL 3D, (depth/biometrics sensor)',
            bluetooth: '5.0, A2DP, LE',
            usb: 'Lightning, USB 2.0',
            sensor: 'Face ID, accelerometer, gyro, proximity, compass, barometer',
            battery: 'Li-Ion 3174 mAh, non-removable (12.08 Wh)'
        }
    },
    {
        id:3,
        name: "Samsung Galaxy S8+ - Silver Gray",
        url: '/samsung-galaxy-s8-plus.png',
        price: 3250000,
        type: 'smartphone',
        popular: true,
        new: false,
        recommended: false,
        stock: 5,
        specifications: {
            brand: 'Samsung',
            size: '6.2 inches',
            display: 'Super AMOLED',
            resolution: '1440 x 2960 pixels, 18.5:9 ratio (~529 ppi density)',
            os: 'Android 7.0 (Nougat), upgradable to Android 9.0 (Pie), One UI',
            prosesor: 'Exynos 8895 (10 nm), Octa-core (4x2.3 GHz Mongoose M2 & 4x1.7 GHz Cortex-A53)',
            gpu: 'Mali-G71 MP20',
            memory: '6GB RAM',
            storage: '128GB UFS 2.1',
            network: 'GSM/HSPA/LTE',
            camera: 'Belakang: 12 MP, f/1.7, 26mm (wide), 1/2.55", 1.4µm, dual pixel PDAF, OIS. Depan: 8 MP, f/1.7, 25mm (wide), 1/3.6", 1.22µm, AF 2 MP (dedicated iris scanner camera)',
            bluetooth: '5.0, A2DP, LE, aptX',
            usb: 'USB Type-C 3.1',
            sensor: 'Iris scanner, fingerprint (rear-mounted), accelerometer, gyro, proximity, compass, barometer, heart rate, SpO2',
            battery: 'Li-Ion 3500 mAh, non-removable (13.48 Wh)'
        }
    },
    {
        id:4,
        name: "Samsung Galaxy Note 8+ - Black",
        url: '/samsung_samsung-galaxy-note-8.png',
        price: 3800000,
        type: 'smartphone',
        popular: true,
        new: false,
        recommended: false,
        stock: 5,
        specifications: {
            brand: 'Samsung',
            size: '6.3 inches',
            display: 'Super AMOLED, HDR10',
            resolution: '1440 x 2960 pixels, 18.5:9 ratio (~521 ppi density)',
            os: 'Android 7.0 (Nougat), upgradable to Android 9.0 (Pie)',
            prosesor: 'Exynos 8895 (10 nm), Octa-core (4x2.3 GHz Mongoose M2 & 4x1.7 GHz Cortex-A53)',
            gpu: 'Mali-G71 MP20',
            memory: '6GB RAM',
            storage: '256GB UFS 2.1',
            network: 'GSM/HSPA/LTE',
            camera: 'Belakang: 12 MP, f/1.7, 26mm (wide), 1/2.55", 1.4µm, dual pixel PDAF, OIS 12 MP, f/2.4, 52mm (telephoto), 1/3.6", 1.0µm, AF, OIS, 2x optical zoom. Depan: 8 MP, f/1.7, 25mm (wide), 1/3.6", 1.22µm, AF 2 MP (dedicated iris scanner camera)',
            bluetooth: '5.0, A2DP, LE, aptX',
            usb: 'USB Type-C 3.1',
            sensor: 'Iris scanner, fingerprint (rear-mounted), accelerometer, gyro, proximity, compass, barometer, heart rate, SpO2',
            battery: 'Li-Ion 3300 mAh, non-removable'
        }
    },
    {
        id:5,
        name: "Iphone 8 Plus - Gold",
        url: '/iphone-8-plus-gold.png',
        price: 3500000,
        type: 'smartphone',
        popular: true,
        new: false,
        recommended: true,
        stock: 4,
        specifications: {
            brand: 'Apple',
            size: '5.5 inches',
            display: 'Retina IPS LCD, 625 nits (typ)',
            resolution: '1080 x 1920 pixels, 16:9 ratio (~401 ppi density)',
            os: 'iOS 11, up to iOS 16.7.11',
            prosesor: 'Apple A11 Bionic (10 nm), Hexa-core (2x Monsoon + 4x Mistral)',
            gpu: 'Apple GPU (three-core graphics)',
            memory: '3GB RAM',
            storage: '256GB NVMe',
            network: 'GSM/CDMA/HSPA/EVDO/LTE',
            camera: 'Belakang: 12 MP, f/1.8, 28mm (wide), 1/3.0", PDAF, OIS 12 MP, f/2.8, 57mm (telephoto), PDAF, 2x optical zoom. Depan: 7 MP, f/2.2, 32mm (standard)',
            bluetooth: '5.0, A2DP, LE',
            usb: 'Lightning, USB 2.0',
            sensor: 'Fingerprint (front-mounted), accelerometer, gyro, proximity, compass, barometer',
            battery: 'Li-Ion 2691 mAh, non-removable (10.28 Wh)'
        }
    },
    {
        id:6,
        name: "Samsung Galaxy S7 Edge - Silver",
        url: '/carousel-samsung-galaxy-s7-edge.png',
        price: 3000000,
        type: 'smartphone',
        popular: false,
        new: false,
        recommended: false,
        stock: 2,
        specifications: {
            brand: 'Samsung',
            size: '5.5 inches',
            display: 'Super AMOLED',
            resolution: '1440 x 2960 pixels, 16:9 ratio (~534 ppi density)',
            os: 'Android 6.0 (Marshmallow), upgradable to Android 8.0 (Oreo), TouchWiz UI',
            prosesor: 'Exynos 8890 Octa (14 nm), Octa-core (4x2.3 GHz Mongoose & 4x1.6 GHz Cortex-A53)',
            gpu: 'Mali-T880 MP12',
            memory: '4GB RAM',
            storage: '128GB UFS 2.0',
            network: 'GSM/HSPA/LTE',
            camera: 'Belakang: 12 MP, f/1.7, 26mm (wide), 1/2.55", 1.4µm, dual pixel PDAF, OIS. Depan: 5 MP, f/1.7, 22mm (wide), 1/4.1", 1.34µm',
            bluetooth: '4.2, A2DP, LE, aptX',
            usb: 'microUSB 2.0, OTG',
            sensor: 'Fingerprint (front-mounted), accelerometer, gyro, proximity, compass, barometer, heart rate, SpO2',
            battery: 'Li-Ion 3600 mAh, non-removable'
        }
    },
    {
        id:7,
        name: "Xiaomi Redmi Note 4 - Black",
        url: '/redmi_note4.png',
        price: 2300000,
        type: 'smartphone',
        popular: true,
        new: false,
        recommended: false,
        stock: 1,
        specifications: {
            brand: 'Xiaomi',
            size: '5.5 inches',
            display: 'IPS LCD',
            resolution: '1080 x 1920 pixels, 16:9 ratio (~401 ppi density)',
            os: 'Android 6.0 (Marshmallow), upgradable to 7.0 (Nougat), MIUI 11',
            prosesor: 'Qualcomm MSM8953 Snapdragon 625 (14 nm), Octa-core 2.0 GHz Cortex-A53',
            gpu: 'Adreno 506',
            memory: '4GB RAM',
            storage: '64GB eMMC 5.1',
            network: 'GSM/HSPA/LTE',
            camera: 'Belakang: 13 MP, f/2.0, 1/3.1", 1.12µm, PDAF. Depan: 5 MP, f/2.0',
            bluetooth: '4.1, A2DP, LE, aptX',
            usb: 'microUSB 2.0, OTG',
            sensor: 'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass',
            battery: 'Li-Po 4100 mAh, non-removable'
        }
    },
    {
        id:8,
        name: "Xiaomi Mi 6 - Black",
        url: '/Mi6.png',
        price: 3600000,
        type: 'smartphone',
        popular: false,
        new: false,
        recommended: false,
        stock: 1,
        specifications: {
            brand: 'Xiaomi',
            size: '5.15 inches',
            display: 'IPS LCD',
            resolution: '1080 x 1920 pixels, 16:9 ratio (~428 ppi density)',
            os: 'Android 7.1.1 (Nougat), upgradable to Android 9.0 (Pie), MIUI 8',
            prosesor: 'Qualcomm MSM8998 Snapdragon 835 (10 nm), Octa-core (4x2.45 GHz Kryo & 4x1.9 GHz Kryo)',
            gpu: 'Adreno 540',
            memory: '6GB RAM',
            storage: '128GB eMMC 5.1',
            network: 'GSM/HSPA/LTE',
            camera: 'Belakang: 12 MP, f/1.8, 27mm (wide), 1/2.9", 1.25µm, PDAF, 4-axis OIS, PDAF, 12 MP, f/2.6, 52mm (telephoto), 1.0µm, AF, 2x optical zoom. Depan: 8 MP',
            bluetooth: '5.0, A2DP, LE, aptX',
            usb: 'USB Type-C',
            sensor: 'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass, barometer',
            battery: 'Li-Po 3350 mAh, non-removable'
        }
    },
    {
        id:9,
        name: "Lenovo LOQ 15 - RTX 3050 6GB",
        url: '/lenovo-loq.png',
        price: 11800000,
        type: 'computer',
        popular: true,
        new: true,
        recommended: true,
        stock: 2,
        specifications: {
            brand: 'Lenovo',
            size: '15.6 inch',
            display: ' IPS 300nits Anti-glare, 100% sRGB, 144Hz, G-SYNC®',
            resolution: '1080 x 1920 pixels',
            os: 'Windows 11 Home + Office Home and Student 2021',
            prosesor: 'Intel® Core™ i5-12450HX, 8C (4P + 4E) / 12T, P-core up to 4.4GHz, E-core up to 3.1GHz, 12MB',
            gpu: 'NVIDIA® GeForce RTX™ 3050 6GB GDDR6, Boost Clock 1732MHz, TGP 95W',
            memory: '12GB RAM',
            storage: '512GB NVMe',
            network: 'Wi-Fi® 6, 11ax 2x2 + BT5.2',
            camera: 'HD 720p with E-shutter',
            bluetooth: 'BT5.2',
            usb: '3x USB-A (USB 5Gbps / USB 3.2 Gen 1), 1x USB-C® (USB 10Gbps / USB 3.2 Gen 2), with Lenovo® PD 140W and DisplayPort™ 1.4, 1x HDMI® 2.1, up to 8K/60Hz',
            // sensor: 'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass',
            battery: 'Integrated 60Wh'
        }
    },
    {
        id:10,
        name: "Acer Nitro V15 - RTX 3050 6GB",
        url: '/Acer-nitro.png',
        price: 9800000,
        type: 'computer',
        popular: true,
        new: true,
        recommended: true,
        stock: 1,
        specifications: {
            brand: 'Acer',
            size: '15.6 inch',
            display: 'IPS-Level Panel 165Hz Refresh Rate',
            resolution: '15.6″ FHD (1920 x 1080) IPS-Level, Refresh Rate : 165Hz',
            os: 'Windows 11 Home + Office Home and Student 2021',
            prosesor: 'AMD Ryzen™ 5 6600H (Boost up to 4.50Ghz) processor',
            gpu: 'NVIDIA® GeForce RTX™ 3050 6GB GDDR6',
            memory: '8GB RAM',
            storage: '512GB NVMe',
            network: 'Wi-Fi6 & Bluetooth® 5.1',
            camera: '720p HD video at 30 fps with Temporal Noise Reduction',
            bluetooth: 'Bluetooth® 5.1',
            usb: 'USB4® 40Gbps, DisplayPort over USB-C, USB charging 5 V; 3 A, DC-in port 20 V; 65 W USB Standard A, Three USB Standard-A ports, supporting:One port for USB 3.2 Gen 1 featuring power off USB chargingTwo ports for USB 3.2 Gen 1HDMI®',
            // sensor: 'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass',
            battery: '57Wh Li ion battery'
        }
    },
    {
        id:11,
        name: "Asus TUF A15 - RTX 3050",
        url: '/asus-tuf.png',
        price: 10000000,
        type: 'computer',
        popular: true,
        new: true,
        recommended: true,
        stock: 5,
        specifications: {
            brand: 'Asus',
            size: '15.6 inch',
            display: ' IPS-level 250nits 1000:1 62.5% sRGB Anti-glare display',
            resolution: '115.6-inch FHD (1920 x 1080) 16:9 144Hz Adaptive-Sync Value',
            os: 'Windows 11 Home + Office Home and Student 2021',
            prosesor: 'AMD Ryzen™ 5 7535HS Processor 3.3GHz (19MB Cache, up to 4.55 GHz, 6 cores, 12 Threads)',
            gpu: 'NVIDIA® GeForce RTX™ 3050 6GB GDDR6',
            memory: '16GB DDR5-5600 SO-DIMM, 2x SO-DIMM slots, Max 32GB',
            storage: '512GB NVMe',
            network: 'Wi-Fi 6(802.11ax) (Dual band) 2*2 + Bluetooth® 5.3 Wireless Card (*Bluetooth® version may change with OS version different.)',
            camera: '720p HD video at 30 fps with Temporal Noise Reduction',
            bluetooth: 'Bluetooth® 5.3',
            usb: '1x RJ45 LAN port; 1x USB 3.2 Gen 2 Type-C support DisplayPort™; 3x USB 3.2 Gen 2 Type-A; 1x HDMI 2.0b; 1x 3.5mm Combo Audio Jack®',
            // sensor: 'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass',
            battery: '48WHrs, 3S1P, 3-cell Li-ion'
        }
    },
    {
        id:12,
        name: "HP Victus 15 - RTX 3050",
        url: '/hp-victus.png',
        price: 10000000,
        type: 'computer',
        popular: false,
        new: true,
        recommended: false,
        stock: 2,
        specifications: {
            brand: 'HP',
            size: '15.6 inch',
            display: 'IPS, micro-edge, anti-glare, 300 nits, 62.5% sRGB',
            resolution: '15.6 inch FHD (1920 x 1080), 144 Hz',
            os: 'Windows 11 Home + Microsoft Office Home and Student 2021 + M365',
            prosesor: 'Intel® Core™ i5-13420H (up to 4.6 GHz with Intel® Turbo Boost Technology, 12 MB L3 cache, 8 cores, 12 threads)',
            gpu: 'NVIDIA® GeForce RTX™ 3050 6GB GDDR6',
            memory: '16 GB DDR4-3200 MT/s (1 x 16 GB)',
            storage: '512 GB PCIe® Gen4 NVMe™ M.2 SSD',
            network: 'ntegrated 10/100/1000 GbE LAN',
            camera: '720p HD video at 30 fps with Temporal Noise Reduction',
            bluetooth: 'Bluetooth® 5.3',
            usb: '1 USB Type-A 5Gbps signaling rate (HP Sleep and Charge); 1 USB Type-A 5Gbps signaling rate; 1 AC smart pin; 1 HDMI 2.1; 1 headphone/microphone combo',
            // sensor: 'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass',
            battery: '3-cell, 52.5 Wh Li-ion polymer'
        }
    }
]